# Generated by Django 3.2.5 on 2021-07-10 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuraCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Fura holati',
                'verbose_name_plural': 'Fura holati',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('salesNumber', models.CharField(blank=True, max_length=50)),
                ('data', models.CharField(max_length=100)),
                ('slaughteredCattle', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('loss', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('purchase', models.FloatField()),
                ('nds', models.PositiveBigIntegerField(default=0.0)),
                ('veterinar', models.FloatField(default=0.0)),
                ('goStandart', models.FloatField(default=0.0)),
                ('gigiena', models.FloatField(default=0.0)),
                ('customer', models.FloatField(default=0.0)),
                ('deklarent', models.FloatField(default=0.0)),
                ('delivery', models.FloatField(default=0.0)),
                ('swift', models.FloatField(default=0.0)),
                ('ministryFinance', models.FloatField(default=0.0)),
                ('certificate', models.FloatField(default=0.0)),
                ('sPOT', models.FloatField(default=0.0)),
                ('sES', models.FloatField(default=0.0)),
                ('thatsall', models.FloatField()),
                ('finisheddate', models.CharField(max_length=100)),
                ('willBePaid', models.FloatField(default=0.0)),
                ('residue', models.FloatField()),
                ('buymonth', models.IntegerField()),
                ('finishedmonth', models.IntegerField()),
                ('comment', models.CharField(max_length=1028)),
                ('accountnumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeapp.accountnumber')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeapp.counterparty')),
                ('furaCondition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesapp.furacondition')),
                ('productname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeapp.productname')),
            ],
            options={
                'verbose_name': 'Sotuvlar',
                'verbose_name_plural': 'Sotuvlar jadvali',
            },
        ),
    ]
